name: flutter_charts_example
description: Projeto para implementação de graficos no flutter.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: any
  cupertino_icons: ^1.0.0
  get: any

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true